language: java
jdk:
- oraclejdk8
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew junitPlatformTest
  - ./gradlew junitPlatformJacocoReport
after_success:
  - bash <(curl -s https://codecov.io/bash)